---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
      - exec
      - patch
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - create
      - delete
      - watch
  - apiGroups:
      - security.openshift.io 
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints 
    verbs: 
      - use
