---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: openshift-backup
  namespace: etcd-backup
spec:
  schedule: "0 12 * * *" # Everyday at noon
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels:
        app: openshift-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-backup
        spec:
          containers:
            - name: backup
              image: regional-quay-quay.apps.hub.vimv2.ecocenter.fr/ocp-utils/backup-cli:latest
              envFrom:
                - secretRef:
                    name: s3-bucket-credentials
                - configMapRef:
                    name: s3-bucket-credentials
              command:
                - "/bin/bash"
                - "-c"
                - |
                  #!/bin/bash

                  MASTER_NODE_IP=$(oc get nodes -l node-role.kubernetes.io/master -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')

                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/id_ed25519 core@$MASTER_NODE_IP 'sudo /usr/local/bin/cluster-backup.sh /tmp/backup-$(date +"%Y%m%d-%H%M%S") && sudo chown -R core:core /tmp/backup*'

                  rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/id_ed25519" -a --info=progress2 core@$MASTER_NODE_IP:/tmp/backup-* /backups

                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/id_ed25519 core@$MASTER_NODE_IP 'rm -rf /tmp/backup*'

                  aws s3 ls s3://${BUCKET_NAME}/ --no-verify-ssl --endpoint-url https://$BUCKET_HOST:$BUCKET_PORT

                  aws s3 sync /backups/ s3://$BUCKET_NAME/ --no-verify-ssl --endpoint-url https://$BUCKET_HOST:$BUCKET_PORT
              volumeMounts:
                - name: ssh-key-secret
                  mountPath: /tmp
                  readOnly: true
                - name: writable-backups
                  mountPath: /backups
          volumes:
            - name: ssh-key-secret
              secret:
                secretName: ssh-key-secret
            - name: writable-backups
              emptyDir: {}
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: ClusterFirst
          serviceAccountName: openshift-backup
