---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd-backup

resources:
# - ns-etcd-backup.yaml
- sa-openshift-backup.yaml
- clusterrole-cluster-etcd-backup.yaml
- clusterrolebinding-openshift-backup.yaml
- cronjob-openshift-backup.yaml

- pod-openshift-backup-test.yaml
