---
apiVersion: v1
kind: Pod
metadata:
  name: openshift-backup-test
  namespace: etcd-backup
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: backup
      image: regional-quay-quay.apps.hub.vimv2.ecocenter.fr/ocp-utils/backup-cli:latest
      command:
        - "/bin/bash"
        - "-c"
        - "while true; do sleep 10; done"
      envFrom:
        - secretRef:
            name: s3-bucket-credentials
        - configMapRef:
            name: s3-bucket-credentials
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: ssh-key-secret
          mountPath: /tmp
          readOnly: true
        - name: writable-ssh-key
          mountPath: /writable
  volumes:
    - name: ssh-key-secret
      secret:
        secretName: ssh-key-secret
    - name: writable-ssh-key
      emptyDir: {}
  restartPolicy: Never
  serviceAccountName: openshift-backup
