---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-lightspeed
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  targetNamespaces:
    - openshift-lightspeed
  upgradeStrategy: Default
