{{- range .Values.providers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .modelName | lower | replace " " "-" }}-credentials
  namespace: openshift-lightspeed
type: Opaque
stringData:
  # https://platform.openai.com/api-keys
  apitoken: {{ .apiToken }}
{{- end }}
